
package com.valil.chesswebservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * A chess web service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://www.valil.com/ChessWebService", wsdlLocation = "http://www.valil.com/ChessWebService/Service.asmx?WSDL")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.valil.chesswebservice.Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.valil.chesswebservice.Service.class.getResource(".");
            url = new URL(baseUrl, "http://www.valil.com/ChessWebService/Service.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.valil.com/ChessWebService/Service.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICE_WSDL_LOCATION = url;
    }

    private static Service SERVICE_INSTANCE;
    public static Service getService()
    {
    	if(SERVICE_INSTANCE==null)
    	{
    		SERVICE_INSTANCE=new Service();
    	}
    	return SERVICE_INSTANCE;
    }
    
    
    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(SERVICE_WSDL_LOCATION, new QName("http://www.valil.com/ChessWebService", "Service"));
    }

    /**
     * 
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(new QName("http://www.valil.com/ChessWebService", "ServiceSoap"), ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.valil.com/ChessWebService", "ServiceSoap"), ServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12() {
        return super.getPort(new QName("http://www.valil.com/ChessWebService", "ServiceSoap12"), ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.valil.com/ChessWebService", "ServiceSoap12"), ServiceSoap.class, features);
    }

}
